pipeline:
  build:
    image: node:latest
    environment:
      - DEBUG=*
    commands:
      - npm install
      - npm install -g mocha
      - npm install -g istanbul
      - npm install -g gulp
      - npm install -g debug

  publish:
    image: plugins/docker
    repo: ncodefresh/demochat
    username: ncodefresh
    password: intercoredockerhub2
    tags: [ "latest", "1" ]
    when:
      branch: master
      event: push

  notify:
    slack:
      image: plugins/slack
      webhook_url: https://hooks.slack.com/services/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
      channel: drone-migration
      username: drone
      template: >
        build #{{ build.number }} finished with a {{ build.status }} status
